name: Cleanup Format Verification

on:
  push:
    branches:
      - release/format-verify

permissions:
  contents: read

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clang-format check
        uses: ./.github/actions/run-clang-format
        with:
          failCondition: error

  gersemi:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: gersemi check
        uses: ./.github/actions/run-gersemi
        with:
          failCondition: error
